version: '3'

volumes:
  pg_data_production:
  static_volume:

networks:
  django-network:
    driver: bridge

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
    networks:
      - django-network
  backend:
    image: tonyrem/taski_backend
    env_file: .env
    volumes:
      - static_volume:/backend_static
    networks:
      - django-network
  frontend:
    image: tonyrem/taski_frontend  # Качаем с Docker Hub
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static
    networks:
      - django-network
  gateway:
    image: tonyrem/taski_gateway  # Качаем с Docker Hub
    env_file: .env
    volumes:
      - static_volume:/staticfiles/
    networks:
      - django-network
    ports:
      - 8000:80